# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - project: templates/ci
    file: default.yml

build:
  extends: .docker-build-multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=registry.timmertech.nl/docker/ubuntu/cache:latest
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB}
    HEALTH_CHECK_UUID: 874cdb73-e521-47fb-a973-61f63a05d387
