default:
  image: registry.timmertech.nl/docker/docker:latest

include:
  - project: templates/ci
    file: docker.yml

stages:
  - build
  - dockerhub

build:
  extends: .docker-build-multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=registry.timmertech.nl/docker/ubuntu:latest
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB}
