image: registry.timmertech.nl/docker/docker:latest

include:
  - project: templates/ci
    file: docker.yml
  - project: templates/ci
    file: docker-hub.yml

build:
  stage: build
  interruptible: true
  only:
    - master
    - schedules
  script:
    - docker build --pull
      --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}"
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      --build-arg CI_PROJECT_NAME=${CI_PROJECT_NAME}
      --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}"
      --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
      --build-arg DOCKER_PROXY=${DOCKER_PROXY_HOST}
      --build-arg UBUNTU_VERSION=`docker run --rm -t ${DOCKER_IMAGE_FROM} cat /etc/os-release|grep VERSION_ID|cut -d '=' -f 2|tr -d '"'|tr -d '\r'`
      --file=${DOCKER_FILE}
      --tag=${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

dockerhub:
  stage: deploy
  extends: .dockerhub
  variables:
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - master
    - schedules
