# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.1.2
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.5.1
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@0.5.1

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.3
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      tag: $DOCKER_IMAGE_PATH:latest
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:latest
      healthcheck-uuid: 874cdb73-e521-47fb-a973-61f63a05d387

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.3
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      tag: $DOCKER_IMAGE_PATH:$CI_COMMIT_TAG
      tags: >-
        --tag=$DOCKER_IMAGE_HUB_PATH:$CI_COMMIT_TAG
