default:
  image: registry.timmertech.nl/docker/docker:latest

include:
  - project: templates/ci
    file: docker.yml

stages:
  - build
  - dockerhub

.build:
  extends: .docker-build-multi
  variables:
    DOCKER_PROXY: "ENABLED"
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_IMAGE_BASE: "ubuntu:latest"
    BUILD_ARGS: >-
      --build-arg DOCKER_IMAGE_BASE=${DOCKER_IMAGE_BASE}

build:
  extends: .build

dockerhub:
  stage: dockerhub
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_HUB}
