#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

UBUNTU_VERSION=`docker run --rm -t ubuntu:latest cat /etc/os-release|grep VERSION_ID|cut -d '=' -f 2|tr -d '"'|tr -d '\r'`

docker build \
		--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
		--build-arg VCS_REF=`git rev-parse --short HEAD` \
		--build-arg DOCKER_IMAGE="${IMAGE_NAME}" \
		--build-arg UBUNTU_VERSION="${UBUNTU_VERSION}" \
		-t $IMAGE_NAME .
